version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: projectlvqi-postgres
    environment:
      POSTGRES_USER: projectlvqi
      POSTGRES_PASSWORD: projectlvqi
      POSTGRES_DB: projectlvqi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: projectlvqi-redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
